project_id: ""
project_name: "SFT Training Project"
dataset_type: sft
data:
  train_file: train.jsonl
  batch_size: 16
model:
  path: Qwen/Qwen3-8B
  qlora_rank: 128
  name: "My SFT Model"
  description: "Supervised fine-tuned model"
trainer:
  num_epochs: 20
  learning_rate: 0.0001
  save_step: 20
